### ISSUE TITLE
Set Bootloader PW

### ISSUE THREAD

**Issue by georgenalen** [ansible-lockdown/UBUNTU20-CIS#1]
Control 1.5.1 - Ensure bootloader password is set

You need to set the boot loader pw for grub. There is a custom module for RHEL that is used for this task. I was not able to get it working with Ubuntu, I am not sure why. We can use shell/command with the grub-mkpasswd-pbkdf2 command. However that command requires a password to be entered twice and I haven't found a good way to work that on the ansible side. The custom module creates a randomized pw to use and hides that random pw, which is great and what I hope to get for this.

**Comment by uk-bolly** [comment]
Adding work for Feb23 _updates

**Comment by uk-bolly** [comment]
hi @georgenalen 

Thank you again for raising this issue. This has now been merged into the devel branch. Aiming to put this into main if all is well in the next couple of weeks.

many thanks again

uk-bolly

**Comment by MrSteve81** [comment]
This was added to PR https://github.com/ansible-lockdown/UBUNTU20-CIS/pull/74 that addressed a lot of fixes.  This has been merged to main.  Thanks @georgenalen  for the find.
