### ISSUE TITLE
6.2.12 fails to run when only rule enabled

### ISSUE THREAD

**Issue by karlg100** [ansible-lockdown/UBUNTU20-CIS#148]
PRELIM for 6.2.12 fails to run when it is the only control enabled. Reference 6.2.12 and the following task. 

https://github.com/ansible-lockdown/UBUNTU20-CIS/blob/09b76de27c75593bf3d82108f3e50d3505899af6/tasks/prelim.yml#L193

**Comment by uk-bolly** [comment]
hi @karlg100 

Thank you again for this issue, this was merged to devel in Jul and now just merged to main.
Please close if you feel this is resolved.

many thanks

uk-bolly
