### ISSUE TITLE
Typo in default/main.yml file

### ISSUE THREAD

**Issue by bstivers** [ansible-lockdown/UBUNTU20-CIS#20]
I feel this is minor as people should be going through the list to see what each control is, but I figured I would mention it anyway in case people are pulling this via git in something like AWX/Tower. If appears as though both devel and main branches have the typo.

Line 325:
```yaml
ubtu20cis_squid_server: fase
```
should be
```yaml
ubtu20cis_squid_server: false
```

**Comment by georgenalen** [comment]
@bstivers,
 Thanks for catching that I will fix it today and get it into devel. 

George

**Comment by georgenalen** [comment]
Addressed in release 1.1.1
