### ISSUE TITLE
Role migration into an Ansible collection?

### ISSUE THREAD

**Issue by jdeppe-35** [ansible-lockdown/UBUNTU20-CIS#21]
Hello

Do you plan to migrate the ansible role "ansiblelockdown/ubuntu20-CIS" into an Ansible collection?

Best

**Comment by uk-bolly** [comment]
hi @jdeppe-35 

Apologies for not responding sooner. We are looking at this as you maybe aware there are multiple repositories and benchmarks that are maintained with more being added and updated taking place. We are hoping to get this out by the end of the quarter(subject to workload).

regards 

uk-bolly

**Comment by uk-bolly** [comment]
Hi @jdeppe-35 

I have enabled the repo to work with collections now. Although long term we don't have any plan currently to create a collection of our own. We will be looking forward and this may yet change,

many thanks

uk-bolly

**Comment by georgenalen** [comment]
Closing this stale issue since we have been collection compliant (not an actual collection) for some time
