### ISSUE TITLE
The audit-related .rules-files miss a new line at EOF

### ISSUE THREAD

**Issue by karniemi** [ansible-lockdown/UBUNTU20-CIS#27]
**Describe the Issue**
The audit-related .rules-files miss a new line at EOF. This produces a faulty configuration. It seems this has been fixed in RHEL8-version, but the fix is missing in other versions of lockdown: https://github.com/ansible-lockdown/RHEL8-CIS/commit/59fd82a57936fe3ba6335f5e531822db2853c833 )

**Expected Behavior**
the audit .rules should have a new line at EOF

**Actual Behavior**
The audit-related .rules-files generated by lockdown miss a new line at EOF. auditd generated a concatenated file using augenrules, and because of the missing new lines, some rules are catenated at the same line, which effectily causes syntax errors for the generated "audit.rules"-files

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**
- not relevant

**Additional Notes**
- not relevant

**Possible Solution**
add the missing new lines in the auditd rule-templates

**Comment by georgenalen** [comment]
@karniemi 
 Thanks for catching that one, I thought I cleaned that up a while ago but it looks I haven't. I'll have the fix merged through. 

George
