### ISSUE TITLE
logrotate permission hardening breaks system logging

### ISSUE THREAD

**Issue by karniemi** [ansible-lockdown/UBUNTU20-CIS#28]
**Describe the Issue**
The steps implemented for "4.4 Ensure logrotate assigns appropriate permissions" in lockdown break system logging. The CIS benchmark gives an example "create 0640 root utmp"  and it seems that this has been taken too literally in the lockdown implementation. The bug is: only the permissions were supposed to be changed - not the ownership of the log files. Now the files get created with ownership "root:utmp", and rsyslog by default is configured to drop privileges to "syslog:syslog". On such system, rsyslog can no more write logs after the first log rotation.

Also, the intention in the CIS Benchmark is to scan also files in /etc/logrotate.d, which is currently skipped by lockdown.

**Expected Behavior**
logs produced after lockdown

**Actual Behavior**
logfiles empty after lockdown -after first logrotate round

**Control(s) Affected**
Version 7:
6.2 Activate audit logging
6.3 Enable Detailed Logging

**Environment (please complete the following information):**
- not relevant

**Additional Notes**
- N/A

**Possible Solution**
Should only set the permission mode in the "create"-line of logrotate-configuration files, and leave the ownership as it is.

**Comment by uk-bolly** [comment]
hi @karniemi 

Thank you for taking the time to raise this issue.
We have merged this fix into the devel and main branches.

Regards

uk-bolly
