### ISSUE TITLE
4.1.2.3 adds admin_space_left_action twice in /etc/audit/auditd.conf

### ISSUE THREAD

**Issue by karniemi** [ansible-lockdown/UBUNTU20-CIS#29]
**Describe the Issue**
4.1.2.3 adds admin_space_left_action twice in /etc/audit/auditd.conf

The problem is in this line, which has " = halt" also in the regexp:
https://github.com/ansible-lockdown/UBUNTU20-CIS/blob/bc0c7b594554a054e429d734677c3c043456236a/tasks/section_4/cis_4.1.2.x.yml#L43

**Expected Behavior**
replace the current admin_space_left_action-entry in /etc/audit/auditd.conf

**Actual Behavior**
adds a new admin_space_left_action-entry in /etc/audit/auditd.conf

**Control(s) Affected**
- dunno

**Environment (please complete the following information):**
 - not relevant

**Additional Notes**
- none

**Possible Solution**
fix the regexp

**Comment by uk-bolly** [comment]
hi @karniemi 

Thank you for taking the time to raise this issue.
We have merged this fix into the devel and main branches.
Please feel free to feedback if you find this is not working as expected.

Regards

uk-bolly
