### ISSUE TITLE
Ensure Root Path Integrity

### ISSUE THREAD

**Issue by georgenalen** [ansible-lockdown/UBUNTU20-CIS#3]
Control 6.2.3 - Ensure root PATH Integrity

We need to figure out the jinja2 filter to use. I pull the paths from $PATH. The control wants all of those paths to exist so I do a stat on them. Which creates a multi dictionary. I can have it do what I need but I want to message out the list of paths that don’t exist. I can get it to list the “exists” value or the “item” value with the map(attribute) however I can’t list the “item” value if “exists” is false. This is the gist of what I’m trying to do {{ ubtu18cis_6_2_7_path_stat.results | selectattr('stat.exists','equalto','false') | map(attribute='item') | list }}". Item is the path even if the file doesn’t exist and is in ubtu18cis_6_2_7_path_stat.results.item in the tree and the exists is in ubtu18cis_6_2_7_path_stat.results.stat.exists of the tree. With that I’m trying to just get the dictionary items where exists is false and list the item value. Hopefully that makes sense, I’ve done that before with single dictionary things but I can’t figure out with the multiple dict stuff.

**Comment by uk-bolly** [comment]
Added to Feb23_updated

**Comment by uk-bolly** [comment]
hi @georgenalen 

Thank you again for raising this issue. This has now been merged into the devel branch. Aiming to put this into main if all is well in the next couple of weeks.

many thanks again

uk-bolly

**Comment by MrSteve81** [comment]
This was added to PR https://github.com/ansible-lockdown/UBUNTU20-CIS/pull/74 that addressed a lot of fixes.  This has been merged to main.  Thanks @georgenalen  for the find.
