### ISSUE TITLE
1.5.4 "Ensure core dumps are restricted": partially implemented

### ISSUE THREAD

**Issue by karniemi** [ansible-lockdown/UBUNTU20-CIS#30]
**Describe the Issue**
CIS v1.1.0 list 3 remediation steps - but ansible-lockdown/UBUNTU20-CIS implements only one of them ("fs.suid_dumpable = 0
")

**Expected Behavior**
should do all the remediation steps

**Actual Behavior**
does only 1/3 of the remediation steps in CIS Benchmark

**Control(s) Affected**
- dunno

**Environment (please complete the following information):**
 - not applicaple

**Additional Notes**
- N/A

**Possible Solution**
- N/A

**Comment by uk-bolly** [comment]
hi @karniemi 

Thank you for taking the time to raise this issue.
We have merged this fix into the devel and main branches.

Regards

uk-bolly
