### ISSUE TITLE
1.1.6-1.1.9 /dev/shm sets non-CIS option "size=2G" by default

### ISSUE THREAD

**Issue by karniemi** [ansible-lockdown/UBUNTU20-CIS#31]
**Describe the Issue**
1.1.6-1.1.9 /dev/shm sets non-CIS option "size=2G" by default. Setting the size is not actually recommended by the CIS Benchmark and not really a hardening step  -  though, it's included in an example in the benchmark document.

Fortunately, the implementation makes it possible to modify the default options using the variable - but still,  the default should not include a non-hardening related size-option.

**Expected Behavior**
Should not set size by default  for /dev/shm.

**Actual Behavior**
Sets size by default for /dev/shm.

**Control(s) Affected**
- dunno
- 
**Environment (please complete the following information):**
 - not applicable

**Additional Notes**
- N/A

**Possible Solution**
- N/A

**Comment by uk-bolly** [comment]
hi @karniemi 

Thank you for taking the time to raise this issue.
We have merged this fix into the devel and main branches.

Regards

uk-bolly
