### ISSUE TITLE
Rule 4.4: create line is a wrong place if there is none already

### ISSUE THREAD

**Issue by CFoltin** [ansible-lockdown/UBUNTU20-CIS#68]
In the following rule

https://github.com/ansible-lockdown/UBUNTU20-CIS/blob/a1f61e2245b787534ce6be7e454d8338704ad154/tasks/section_4/cis_4.4.yml#L6

the create statement will be placed at the wrong line if there is no create statement at the beginning of a line.
This doesn't work as it is ignored by logrotate. 
Put the following rule instead:

       lineinfile:
        path: "{{ item.path }}"
        regexp: '^\s*create\s\s*[0-9]'
        line: 'create {{ ubtu20cis_logrotate_create_settings }}'
        insertbefore: '^}'

**Comment by uk-bolly** [comment]
hi @CFoltin 

Thank you again for raising this issue. This has now been merged into the devel branch. Aiming to put this into main if all is well in the next couple of weeks.

many thanks again

uk-bolly

**Comment by MrSteve81** [comment]
This was added to PR https://github.com/ansible-lockdown/UBUNTU20-CIS/pull/74 that addressed a lot of fixes.  This has been merged to main.  Thanks @CFoltin for the find.
