### ISSUE TITLE
Rule 1.4.1 typo and doesn't work unless lines already exist (cis_2.0.1 branch)

### ISSUE THREAD

**Issue by dderemiah** [ansible-lockdown/UBUNTU20-CIS#88]
**Describe the Issue**
Fails to create a bootloader line on fresh installs where the line doesn't already exist

**Expected Behavior**
Should create the bootloader line even if the entries are not there yet

**Actual Behavior**

**Control(s) Affected**
1.4.1 Ensure bootloader password

**Environment (please complete the following information):**
 - Ansible Version:  ansible [core 2.15.2]
 - Host Python Version: Python 3.8.10
 - Ansible Server Python Version: Python 3.10.12
 - Additional Details: branch is cis_2.0.1

**Additional Notes**
Anything additional goes here

**Possible Solution**
Enter a suggested fix here

**Comment by uk-bolly** [comment]
hi @dderemiah 

Thank you for raising this issue, apologies for the time it has taken to get addressed. We believe it the fix has now been applied and merged today.
Please let us know if this is still an issue?

many thansk

uk-bolly

**Comment by uk-bolly** [comment]
hi @dderemiah 

Have managed to fix the issue with the pipeline and all is now merged into devel. Thank you again fr your feedback and PR.


uk-bolly
